name: Test

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        pip install pytest
        pip install click
        pip install joblib
        pip install sklearn
        pip install pandas
        pip install numpy
        pip install mlflow
        pip install flake8
        pip install black
        pip install mypy
    - name: Poetry configuration
      run: |
        poetry env use python3.9
        poetry add click
        poetry add joblib
        poetry add sklearn
        poetry add pandas
        poetry add numpy
        poetry add mlflow
        poetry install
        poetry update
    - name: Test
      run: |
        poetry run pytest
    - name: Lint
      run: |
        black src/
        flake8 src/
        mypy src/
